### ISSUE TITLE
SIP Register

### ISSUE THREAD

**Issue by wnieves19** [davehorton/drachtio-srf#17]
I'm trying to use drachtio-srf to register to a SIP server and be able to handle invites, however I'm having trouble registering, I'm receiving a 401 Unauthorized.  I'm sending the following request upon successfully connecting to the drachtio-server

`

        srf.on("connect", (err, hostport) => {
        if (err) return console.log("error connecting: ${err}");
        srf.request({
            uri : "sip:<sip host>:5060",
            method: "REGISTER",
            headers: {
                "From": "sip:<sip username>@<sip host>",
                "To": "sip:<sip username@<sip host>",
                "User-Agent" : "drachtio-srf",
            },
            auth: {
                username: "<sip username>,
                password: "<sip password>"
            }
        }, function(err, req){
            if( err ) { throw err ; }
            req.on("response", function(res) {
                if( res.status < 200 ) {
                    console.log("Response " + res.status)
                    return; }
                if( 200 !== res.msg.status) {
                    console.log("Error registering: " + res.msg.status);
                }else {
                    console.log("registered successfully");
                }
            });
        });

    })`

I have access to the SIP traces of the server I'm trying to connect to, and I get the following error message: The SIP subscriber failed to register. Error: No authentication message received.  I read that by providing the "auth" in drachtio-srf it takes care of answering the challenge, but I don't know if that is happening.  I'm using drachtio-srf 4.3.0

**Comment by davehorton** [comment]
That should work. I will try to put a test case together to see if there is a bug

**Comment by davehorton** [comment]
I added a test case for this, and it works for me.  Can you show a trace from the drachtio server log for your failing scenario?

**Comment by wnieves19** [comment]
This is a log from the drachtio-server as soon as I try to register from drachtio-srf.  We've tried to register in this same environment using other SIP clients and it worked. 

2018-07-09 11:46:10.680796 Received connection from client at 127.0.0.1:62148
2018-07-09 11:46:10.683104 Client::processAuthentication - validating secret cymru
2018-07-09 11:46:10.689306 Client::processAuthentication - secret validated successfully: cymru
2018-07-09 11:46:10.689384 Sending response: 199#e6382c61-22ce-46fa-9a81-9e643b2a646a|response|7da81b9d-5046-48b4-98b5-c6ce6f190eff|OK|tcp/[::1]:5060,udp/[::1]:5060,udp/127.0.0.1:5060,tcp/127.0.0.1:5060,tcp/192.168.1.151:5060,udp/192.168.1.151:5060

2018-07-09 11:46:10.703485 Sending response: 85#f0a42b04-c94b-4aaa-9b54-3d34cd71a215|response|9d0dc9d5-f1e3-45fa-9815-15f9b807a503|OK

2018-07-09 11:46:10.710019 nta.c:2753 nta_tpn_by_url() nta: selecting scheme sip
2018-07-09 11:46:10.710128 nta.c:2595 outgoing_update_contact() outgoing_update_contact: updating contact to  udp/192.168.1.151:5060
2018-07-09 11:46:10.710193 tport.c:3285 tport_tsend() tport_tsend(0x7fcf59f15980) tpn = */192.168.1.1:5060
2018-07-09 11:46:10.710259 tport.c:4085 tport_resolve() tport_resolve addrinfo = 192.168.1.1:5060
2018-07-09 11:46:10.710355 tport.c:3531 tport_send_msg() tport_vsend returned 498
2018-07-09 11:46:10.710521 send 498 bytes to udp/[192.168.1.1]:5060 at 11:46:10.710318:
REGISTER sip:192.168.1.1 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.151;rport;branch=z9hG4bKFcNj7vD4cp4HB
Max-Forwards: 70
From: <sip:<sip username>@192.168.1.1>;tag=DtZZ7rZ523tUa
To: <sip:<sip username>@192.168.1.1>
Call-ID: 0b26237d-fe32-1236-4f9e-151bd8a38bb8
CSeq: 125239521 REGISTER
Expires: 300
User-Agent: drachtio-srf
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length: 0
Contact: <sip:<sip username>@192.168.1.151:5060;transport=udp>
 
2018-07-09 11:46:10.710590 nta.c:8395 outgoing_send() nta: sent REGISTER (125239521) to */192.168.1.1:5060
2018-07-09 11:46:10.710644 tport.c:4199 tport_pend() tport_pend(0x7fcf59f15980): pending 0x7fcf59f1a5f0 for udp/192.168.1.151:5060 (already 0)
2018-07-09 11:46:10.710694 nta.c:1352 set_timeout() nta: timer set to 32000 ms
2018-07-09 11:46:10.710745 nta.c:1350 set_timeout() nta: timer shortened to 1000 ms
2018-07-09 11:46:10.710803 nta.c:4559 nta_leg_destroy() nta_leg_destroy(0x7fcf59f16dd0)
2018-07-09 11:46:10.731015 tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7fcf59f15980): events IN
2018-07-09 11:46:10.731150 tport.c:2892 tport_recv_event() tport_recv_event(0x7fcf59f15980)
2018-07-09 11:46:10.731238 tport.c:3233 tport_recv_iovec() tport_recv_iovec(0x7fcf59f15980) msg 0x7fcf59d13180 from (udp/192.168.1.151:5060) has 510 bytes, veclen = 1
2018-07-09 11:46:10.731507 recv 494 bytes from udp/[192.168.1.1]:5060 at 11:46:10.731332:
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.1.151;received=192.168.92.2;rport=5060;branch=z9hG4bKFcNj7vD4cp4HB
From: <sip:<sip username>@192.168.1.1>;tag=DtZZ7rZ523tUa
To: <sip:<sip username>@192.168.1.1>;tag=sip+1+ce47002d+190f9835
Call-ID: 0b26237d-fe32-1236-4f9e-151bd8a38bb8
CSeq: 125239521 REGISTER
WWW-Authenticate: Digest realm="<host IP>", nonce="8a30e2dbdb9f", stale=false, algorithm=MD5, qop="auth"
Server: DC-SIP/2.0
Organization: Metaswitch Networks
Content-Length: 0
 
2018-07-09 11:46:10.731590 tport.c:3051 tport_deliver() tport_deliver(0x7fcf59f15980): msg 0x7fcf59d13180 (494 bytes) from udp/192.168.1.1:5060 next=0x0
2018-07-09 11:46:10.731660 nta.c:3388 agent_recv_response() nta: received 401 Unauthorized for REGISTER (125239521)
2018-07-09 11:46:10.731752 nta.c:3455 agent_recv_response() nta: 401 Unauthorized is going to a transaction
2018-07-09 11:46:10.731847 nta.c:9659 outgoing_estimate_delay() nta_outgoing: RTT is 21.65 ms
2018-07-09 11:46:10.731920 tport.c:4261 tport_release() tport_release(0x7fcf59f15980): 0x7fcf59f1a5f0 by 0x7fcf59f1b310 with 0x7fcf59d13180
2018-07-09 11:46:10.748546 nta.c:2753 nta_tpn_by_url() nta: selecting scheme sip
2018-07-09 11:46:10.748649 nta.c:2595 outgoing_update_contact() outgoing_update_contact: updating contact to  udp/192.168.1.151:5060
2018-07-09 11:46:10.748740 tport.c:3285 tport_tsend() tport_tsend(0x7fcf59f15980) tpn = */192.168.1.1:5060
2018-07-09 11:46:10.748805 tport.c:4085 tport_resolve() tport_resolve addrinfo = 192.168.1.1:5060
2018-07-09 11:46:10.748917 tport.c:3531 tport_send_msg() tport_vsend returned 719
2018-07-09 11:46:10.749137 send 719 bytes to udp/[192.168.1.1]:5060 at 11:46:10.748864:
REGISTER sip:192.168.1.1 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.151;rport;branch=z9hG4bKgNeB9Qy79yt4p
Max-Forwards: 70
From: <sip:<sip username>@192.168.1.1>;tag=DtZZ7rZ523tUa
To: <sip:<sip username>@192.168.1.1>
Call-ID: 0b26237d-fe32-1236-4f9e-151bd8a38bb8
CSeq: 125239522 REGISTER
Expires: 300
User-Agent: drachtio-srf
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Authorization: Digest username="<sip username>", realm="<host IP>", nonce="8a30e2dbdb9f", uri="sip:192.168.1.1", algorithm="MD5", response="97711741c74fa6d310c43194fcf45333", qop="auth", nc="00000001", cnonce="cbc70a3c"
Content-Length: 0
Contact: <sip:<sip username>@192.168.1.151:5060;transport=udp>
 
2018-07-09 11:46:10.749197 nta.c:8395 outgoing_send() nta: sent REGISTER (125239522) to */192.168.1.1:5060
2018-07-09 11:46:10.749248 tport.c:4199 tport_pend() tport_pend(0x7fcf59f15980): pending 0x7fcf5b0031b0 for udp/192.168.1.151:5060 (already 0)
2018-07-09 11:46:10.749313 nta.c:4559 nta_leg_destroy() nta_leg_destroy(0x7fcf5b001930)
2018-07-09 11:46:10.771016 tport.c:2777 tport_wakeup_pri() tport_wakeup_pri(0x7fcf59f15980): events IN
2018-07-09 11:46:10.771144 tport.c:2892 tport_recv_event() tport_recv_event(0x7fcf59f15980)
2018-07-09 11:46:10.771250 tport.c:3233 tport_recv_iovec() tport_recv_iovec(0x7fcf59f15980) msg 0x7fcf5b001b80 from (udp/192.168.1.151:5060) has 510 bytes, veclen = 1
2018-07-09 11:46:10.771507 recv 494 bytes from udp/[192.168.1.1]:5060 at 11:46:10.771343:
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.1.151;received=192.168.92.2;rport=5060;branch=z9hG4bKgNeB9Qy79yt4p
From: <sip:<sip username>@192.168.1.1>;tag=DtZZ7rZ523tUa
To: <sip:<sip username>@192.168.1.1>;tag=sip+1+ce47002d+b4020a52
Call-ID: 0b26237d-fe32-1236-4f9e-151bd8a38bb8
CSeq: 125239522 REGISTER
WWW-Authenticate: Digest realm="<host IP>", nonce="8a30e2dddba1", stale=false, algorithm=MD5, qop="auth"
Server: DC-SIP/2.0
Organization: Metaswitch Networks
Content-Length: 0
 
2018-07-09 11:46:10.771590 tport.c:3051 tport_deliver() tport_deliver(0x7fcf59f15980): msg 0x7fcf5b001b80 (494 bytes) from udp/192.168.1.1:5060 next=0x0
2018-07-09 11:46:10.771664 nta.c:3388 agent_recv_response() nta: received 401 Unauthorized for REGISTER (125239522)
2018-07-09 11:46:10.771749 nta.c:3455 agent_recv_response() nta: 401 Unauthorized is going to a transaction
2018-07-09 11:46:10.771825 nta.c:9659 outgoing_estimate_delay() nta_outgoing: RTT is 23.082 ms
2018-07-09 11:46:10.771892 tport.c:4261 tport_release() tport_release(0x7fcf59f15980): 0x7fcf5b0031b0 by 0x7fcf5b003b80 with 0x7fcf5b001b80
2018-07-09 11:46:11.714483 nta.c:1298 agent_timer() nta: timer set next to 4018 ms
2018-07-09 11:46:15.631677 Client::read_handler - bouncing client due to error reading: asio.misc:2
2018-07-09 11:46:15.736705 nta.c:9192 outgoing_timer_dk() nta: timer K fired, terminate REGISTER (125239521)
2018-07-09 11:46:15.736841 nta.c:8890 outgoing_reclaim_queued() outgoing_reclaim_all(0x0, 0x0, 0x7ffee67ec470)
2018-07-09 11:46:15.736932 nta.c:9020 _nta_outgoing_timer() nta_outgoing_timer: 0/0 resent, 0/0 tout, 1/2 term, 1/2 free
2018-07-09 11:46:15.737007 nta.c:1298 agent_timer() nta: timer set next to 35 ms
2018-07-09 11:46:15.777166 nta.c:9192 outgoing_timer_dk() nta: timer K fired, terminate REGISTER (125239522)
2018-07-09 11:46:15.777309 nta.c:8890 outgoing_reclaim_queued() outgoing_reclaim_all(0x0, 0x0, 0x7ffee67ec470)
2018-07-09 11:46:15.777411 nta.c:9020 _nta_outgoing_timer() nta_outgoing_timer: 0/0 resent, 0/0 tout, 1/1 term, 1/1 free
2018-07-09 11:46:15.777480 nta.c:1291 agent_timer() nta: timer not set
2018-07-09 11:46:21.557931 size of hash table for dialogs                                   31
2018-07-09 11:46:21.558157 number of server-side transactions in the hash table             0
2018-07-09 11:46:21.558300 number of client-side transactions in the hash table             0
2018-07-09 11:46:21.558488 number of dialogs in the hash table                              0
2018-07-09 11:46:21.558617 number of sip messages received                                  8
2018-07-09 11:46:21.558731 number of sip messages sent                                      6
2018-07-09 11:46:21.558842 number of sip requests received                                  0
2018-07-09 11:46:21.558985 number of sip requests sent                                      6
2018-07-09 11:46:21.559101 number of in-dialog server transactions created                  0
2018-07-09 11:46:21.559229 number of SIP requests sent by stack                             6
2018-07-09 11:46:21.559325 number of SIP responses sent by stack                            0
2018-07-09 11:46:21.559419 number of SIP requests retransmitted by stack                    0
2018-07-09 11:46:21.559528 number of SIP responses retransmitted by stack                   0
2018-07-09 11:46:21.559640 number of retransmitted SIP requests received by stack           0
2018-07-09 11:46:21.559774 general queue size:                                              0
2018-07-09 11:46:21.559864 timer A queue size:                                              0
2018-07-09 11:46:21.559952 timer B queue size:                                              0
2018-07-09 11:46:21.560062 timer C queue size:                                              0
2018-07-09 11:46:21.560153 timer D queue size:                                              0
2018-07-09 11:46:21.560258 timer E queue size:                                              0
2018-07-09 11:46:21.560351 timer F queue size:                                              0
2018-07-09 11:46:21.560434 timer G queue size:                                              0
2018-07-09 11:46:21.560538 timer K queue size:                                              0
2018-07-09 11:46:21.560644 SipProxyController storage counts
2018-07-09 11:46:21.560750 ----------------------------------
2018-07-09 11:46:21.560877 m_mapCallId2Proxy size:                                          0
2018-07-09 11:46:21.560972 m_mapNonce2Challenge size:                                       0
2018-07-09 11:46:21.561085 general queue size:                                              0
2018-07-09 11:46:21.561204 timer A queue size:                                              0
2018-07-09 11:46:21.561295 timer B queue size:                                              0
2018-07-09 11:46:21.561407 timer C queue size:                                              0
2018-07-09 11:46:21.561559 timer D queue size:                                              0
2018-07-09 11:46:21.561689 timer E queue size:                                              0
2018-07-09 11:46:21.561775 timer F queue size:                                              0
2018-07-09 11:46:21.561861 timer G queue size:                                              0
2018-07-09 11:46:21.561938 timer K queue size:                                              0
2018-07-09 11:46:21.562032 m_mapUri2InvalidData size:                                       0

**Comment by davehorton** [comment]
Is there any reason you are not providing a `realm` value in your challenge?
`WWW-Authenticate: Digest realm="", nonce="8a30e2dbdb9f", stale=false, algorithm=MD5, qop="auth"
`

The problem then is that the username field is empty in your second REGISTER:
`Authorization: Digest username="", ..`

That makes me believe either you are not putting the auth.username value in correctly when you call `srf.request` or I have an issue dealing with a non-existent realm.  If I look at your original code, it does seem wrong in that there is a missing double quote, but I thought maybe this was a cut-and-paste error:

```js
auth: {
            username: "<sip username>,
            password: "<sip password>"
        }
```
Note the missing double quote after username.

Can you verify your code, and also test when providing a realm value?

**Comment by wnieves19** [comment]
I must've remove it when I copied the log here, but it is there, I just tried again and the issue persists.

**Comment by davehorton** [comment]
Did you test with your server providing a realm value?

**Comment by wnieves19** [comment]
Yes, here's my second register from the drachtio-server log

REGISTER sip:<host IP> SIP/2.0
Via: SIP/2.0/UDP 192.168.0.102;rport;branch=z9hG4bKa85gKDHgHZS9c
Max-Forwards: 70
From: <sip:<sip username>@<host IP>>;tag=6UvcD8vy17SSH
To: <sip:<sip username>@<host IP>>
Call-ID: 53c3948b-fe40-1236-e980-c1ba16c56e47
CSeq: 125242589 REGISTER
Expires: 300
User-Agent: drachtio-srf
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Authorization: Digest username="<sip username>", realm="<host IP>", nonce="8a31226f1b34", uri="sip:<host IP>", algorithm="MD5", response="1ef369b330a04ebf60de35f90ee6cfff", qop="auth", nc="00000001", cnonce="d2fd4cfb"
Content-Length: 0
Contact: <sip:<sip username>@192.168.0.102:5060;transport=udp>

**Comment by davehorton** [comment]
I think I will need to see the whole log.

I just tested with an empty realm, and it does work for me.  Let's go back to the original server challenge with the empty realm and try to work out why your's fails.  

Please re-run the test with the following DEBUG:

`DEBUG=drachtio:agent node app.js` (or index.js, whatever is your main file).

There will be a lot of debug output to the console, but the important lines will look something like this:

```
 drachtio:agent WireProtocol#_onData: got message 13170c9e-722b-4a4a-a3ed-8bd16ddb3cf8|sip|network|389|udp|172.29.0.17|5060|17:37:23.053043|f12379ad-bdac-48a7-a43c-9d5a9709a282||
  drachtio:agent SIP/2.0 401 Unauthorized
  drachtio:agent Via: SIP/2.0/UDP 172.29.0.10;rport;branch=z9hG4bK367HNXUej3KvS
  drachtio:agent From: <sip:dhorton@sip.drachtio.org>;tag=3yH92Q87m7v2e
  drachtio:agent To: <sip:dhorton@sip.drachtio.org>;tag=1SIPpTag011
  drachtio:agent Call-ID: 942b6787-fe41-1236-6199-0242ac1d000a
  drachtio:agent CSeq: 125242857 REGISTER
  drachtio:agent WWW-Authenticate: Digest realm="", nonce="8a30e2dbdb9f", stale=false, algorithm=MD5, qop="auth"
  drachtio:agent Content-Length: 0
  drachtio:agent 
  drachtio:agent  +430ms
  drachtio:agent tokens: ["13170c9e-722b-4a4a-a3ed-8bd16ddb3cf8","sip","network","389","udp","172.29.0.17","5060","17:37:23.053043","f12379ad-bdac-48a7-a43c-9d5a9709a282","",""] +436ms
  drachtio:agent received sip response +0ms
  drachtio:agent Agent#handle: got a response with status: 401 +1ms
  drachtio:agent options: {"method":"REGISTER","headers":{"To":"sip:dhorton@sip.drachtio.org","From":"sip:dhorton@sip.drachtio.org;tag=3yH92Q87m7v2e","Contact":"<sip:dhorton@localhost>;expires=3600","content-length":0,"CSeq":"125242858 REGISTER","call-id":"942b6787-fe41-1236-6199-0242ac1d000a","Authorization":"Digest username=\"foo\",realm=\"\",nonce=\"8a30e2dbdb9f\",uri=\"sip:sipp-uas-auth-register-no-realm\",response=\"bb7ada43fec3be677ccd9089f09d854d\",qop=\"auth\",nc=\"00000001\",cnonce=\"97268b30\""},"auth":{"username":"foo","password":"bar"},"uri":"sip:sipp-uas-auth-register-no-realm"} +2ms
```

I want to see why the username in the second REGISTER was empty.

Save off the entire drachtio-server log as well, in case I need to look at that..

**Comment by davehorton** [comment]
Oh, wait......I see the problem.  Please try it this way:

```js
srf.request('sip:<sip host>', {
        method: "REGISTER",
        headers: {
            "From": "sip:<sip username>@<sip host>",
            "To": "sip:<sip username@<sip host>",
            "User-Agent" : "drachtio-srf",
        },
        auth: {
            username: "<sip username>,
            password: "<sip password>"
        }
```

**Comment by wnieves19** [comment]
Still no luck with the syntax change.  Is there anything specific I have to change in the drachtio-server config file for it to be able to register?

**Comment by davehorton** [comment]
No, there is no server configuration required.

Please run it with the DEBUG= command as above, and provide the full output on the console as well as the full drachtio-server log.  If its verbose maybe create a gist and just put a link to it.

**Comment by wnieves19** [comment]
I just ran the test with DEBUG, here's a gist of the output: https://gist.github.com/wnieves19/f6e5251fe235531ff00e03e6b7f39241#file-gistfile1-txt

**Comment by davehorton** [comment]
OK, with the correct syntax at least the username field is being populated now, so it looks like we have moved on to some other problem.

I note that now instead of no realm, you have the server providing a realm which is an IP address.  That is not the typical usage (typically the realm would be a domain name of some sort that defines an authentication realm), but I can't say it is necessarily the problem.

However, your server is responding to the second REGISTER (the one that has credentials) with a 401, whereas it should respond with a 403 Forbidden if the credentials were invalid (or a 200 OK if they were not).  That does seem strange to me.

You have said that other clients register successfully with the same server using the same credentials.  At this point, I would like to see a trace (pcap file) of such a registration, so I can be sure we are really mimicing the same scenario.  For instance, you started with no realm, now we have a realm with IP address -- I'd like to see exactly what the other clients that work are receiving.

Can you register a softphone against that same server, using the same credentials and capture a pcap from your laptop and post that?

**Comment by davehorton** [comment]
just checking back on this...any chance of seeing a pcap using same credentials from softphone?

**Comment by wnieves19** [comment]
I was able to finally register,  the issue was that my SIP provider strictly follows the RFC 2617 standard for HTTP Authentication, so it requires that the "nc" and "algorithm" parameters in The Authorization Request Header that are sent on the challenge response omit quotation marks for their values.  By changing the _compileParams() function in digest-client.js I was able to remove the quotation marks and then it worked.

**Comment by salihy** [comment]
I think I have a similar problem when starting a call. I attached logs from both drachtio and softphone. The only difference I see is softphone has "algorithm" in authentication header, drachtio hasn't.

[logs.zip](https://github.com/davehorton/drachtio-srf/files/2759178/logs.zip)

Thanks.

**Comment by davehorton** [comment]
I agree it seems like the only difference.  Per RFC 7616, this is supposed to be optional:
```
algorithm

A string indicating an algorithm used to produce the digest and an
      unkeyed digest.  If this is not present, it is assumed to be
      "MD5". 
```
Is there any chance you can ask the VoIP provider you are using if they require this field for some reason?

**Comment by salihy** [comment]
I asked them, they said they are either don't know or didn't want to help, is there any way I can add algorithm field to Invite authentication field?

**Comment by davehorton** [comment]
I just pushed a new branch 'set-algo', can you test your code with that and let me know if it resolves the issue?

**Comment by salihy** [comment]
Hi, Thanks for help, I tested it, your fix works but it didn't fix the issue, since my problem seems different than this, i will close this issue, I will also add new log file, if you see anything unusual please let me know. thanks.
[log.zip](https://github.com/davehorton/drachtio-srf/files/2777762/log.zip)

**Comment by salihy** [comment]
i think it is because I am passing request object directly to createb2bua function, how can I alter 'from' field?

**Comment by davehorton** [comment]
Sorry not to reply earlier, you can also simply set that in the call to createB2BUA, ie
```
srf.createB2BUA(req, res, uri, { callingNumber: '+16173333456'})
```
